### ISSUE TITLE
does not support .Net Core

### ISSUE THREAD

**Issue by vikasNew** [IonKiwi/lz4.net#11]
Hello,

when i install this package in my .Net Core project then i get the following message.

package 'lonkiwi.lz4.net 1.0.11' was restored using '.NetFramework Version=v4.6.1' instead of the project target framework '.NetCoreApp,Version=v2.1'. This package may not be fully compatoble with your project.

Please tell me how to resolve this.

**Comment by IonKiwi** [comment]
Hi,

Unfortunately there is no .NET Core support. This project is a wrapper around the original LZ4 written in C, .NET Core does not support C++/CLI (maybe in .NET Core 3.0). This project will not support .NET Core anytime soon. There are other projects that do provide a .NET Standard implementation like https://github.com/MiloszKrajewski/K4os.Compression.LZ4.

**Comment by IonKiwi** [comment]
Just created a managed version (.NET Standard 2.0+, works on .NET Core)
https://github.com/IonKiwi/lz4.managed
https://www.nuget.org/packages/IonKiwi.lz4.managed
