### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by AlexxEG** [IonKiwi/lz4.net#12]
Was wondering if you could update the package on NuGet.org? I want to be able to disable the VC check. I've tried to compile it myself, but it threw errors when I tried to use it in my program.

(Sorry if this isn't a proper way to use issues, feel free to delete this)

**Comment by IonKiwi** [comment]
It's available now
https://www.nuget.org/packages/IonKiwi.lz4.net/1.0.12

**Comment by AlexxEG** [comment]
Thank you!
