### ISSUE TITLE
Content truncated when using LZ4Stream.CreateCompressor() 

### ISSUE THREAD

**Issue by MDNion** [IonKiwi/lz4.net#13]
When compressing a large amount of data, 5471323 bytes, and then decompressing using another library, lz4js, the final resulting data was truncated to 5439489 bytes.  The data did appear to be decoded correctly up to that point.
  
So I ran a little test by just compressing "This is a test. 12345678910" and noticed in the debugger that the compressed data was only 7 bytes.  3 bytes minimum for the LZ4 Frame header and 4 bytes for the block header (BlockSize) equals 7, so that means it was an empty block.
 
Here's the compression logic being used:

```
public static string CompressToLZ4FrameFormat(string inputString, StringBuilder logMessages, out int len)
        {
            using (var innerStream = new MemoryStream())
            using (var stream = lz4.LZ4Stream.CreateCompressor(innerStream, lz4.LZ4StreamMode.Write, LZ4FrameBlockMode.Linked, LZ4FrameBlockSize.Max64KB, LZ4FrameChecksumMode.Content, null, false))
            {  
                byte[] inputArray = UTF8Encoding.UTF8.GetBytes(inputString);
                len = inputArray.Length;

                // Write uncompressed data to the lz4 stream which will compress it and write it to the innerStream.
                stream.Write(inputArray, 0, inputArray.Length);

                var compressed = innerStream.ToArray();
                logMessages.AppendLine("CompressToLZ4FrameFormat(): Before conversion to Base64, compressed.Length=" + compressed.Length);
                return Convert.ToBase64String(compressed);
            }
        }

```
Is this a bug or am I missing something?

**Comment by MDNion** [comment]
I forgot about the Magic Number and the End Mark.  So the minimum size of a frame containing an empty block would be 15 bytes (4 bytes for Magic Number + 3 bytes for Frame Header + 4 bytes for BlockSize + 4 bytes for End Mark), if I understand the [specification](https://github.com/lz4/lz4/blob/master/doc/lz4_Frame_format.md) correctly.
  
And a skippable frame containing 0 bytes of user data would be 8 bytes (4 bytes for Magic Number + 4 bytes for Frame Size + 0 bytes of user data).
  
So the 7 bytes returned by LZ4Stream could not be correct.

**Comment by IonKiwi** [comment]
The lz4 stream writes (the remaining) data when disposed.

In the above code
```
innerStream.ToArray()
```
is called before the lz4 stream is disposed and has not written all data yet to innerStream.

Call innerStream.ToArray after disposing the lz4 compressor like:

```
public static string CompressToLZ4FrameFormat(string inputString, StringBuilder logMessages, out int len) {
	using (var innerStream = new MemoryStream()) {
		using (var stream = lz4.LZ4Stream.CreateCompressor(innerStream, lz4.LZ4StreamMode.Write, LZ4FrameBlockMode.Linked, LZ4FrameBlockSize.Max64KB, LZ4FrameChecksumMode.Content, null, false)) {
			byte[] inputArray = UTF8Encoding.UTF8.GetBytes(inputString);
			len = inputArray.Length;

			// Write uncompressed data to the lz4 stream which will compress it and write it to the innerStream.
			stream.Write(inputArray, 0, inputArray.Length);
		}
                // lz4 'stream' is disposed, and all data has been written to 'innerStream'
		var compressed = innerStream.ToArray();
		logMessages.AppendLine("CompressToLZ4FrameFormat(): Before conversion to Base64, compressed.Length=" + compressed.Length);
		return Convert.ToBase64String(compressed);
	}
}
```

**Comment by MDNion** [comment]
Yes, that works.  Thanks.
