### ISSUE TITLE
Initialization error.

### ISSUE THREAD

**Issue by ghost** [IonKiwi/lz4.net#3]
Hey Kiwi, 

I get the following error while using the lz4Stream.

> "The type initializer for 'Module' threw an exception."

Am I doing something wrong?
Using .NET 4 and VS 2012.
Cheers.

**Comment by IonKiwi** [comment]
Do you have some more information, like the full stack trace?

**Comment by IonKiwi** [comment]
Closing for now. Feel free to reopen if you have more information.
