### ISSUE TITLE
c# embed as resource

### ISSUE THREAD

**Issue by itapi** [IonKiwi/lz4.net#5]
hello! 

I use this amazing wrapper and I want to include the lz4 dll in my exe-In other words to use it as embedded resource and load it in run time.

Now  there are 3 dlls, the x64,x86 and the `lz4.AnyCpuLoader.dll` Do I have to embed them all?

Also tried to  change the `Embed Interop Types` on the `lz4.AnyCpuLoader` reference properties...and got the following error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1759	Cannot embed interop types from assembly 'lz4.AnyCPU.loader, Version=1.0.8.0, Culture=neutral, PublicKeyToken=7aa3c636ef56b77f' because it is missing either the 'System.Runtime.InteropServices.ImportedFromTypeLibAttribute' attribute or the 'System.Runtime.InteropServices.PrimaryInteropAssemblyAttribute' attribute.	iFilter	C:\Users\איתמר\Desktop\itamar\iFilter\iFilter\CSC	1	Active

**Comment by IonKiwi** [comment]
Hi,

The latest release, 1.0.9, now supports loading the lz4.x86.dll/lz4.x64.dll as embedded resource from lz4.AnyCPU.loader.dll.
Using the embedded resource option (enabled by default), only lz4.AnyCPU.loader.dll is required.

As for 'Embed Interop Types' that is for a different kind of interop and not for C++ /cli.

**Comment by itapi** [comment]
@IonKiwi  alright! but how I includ the `lz4.AnyCPU.loader.dll` itself in the project?

**Comment by IonKiwi** [comment]
When you don't want it as regular assembly reference but want to embed it in a self-contained executable, you could do something similar as lz4.AnyCPU.loader.dll uses to load lz4.x86.dll/lz4.x64.dll. Include lz4.AnyCPU.loader.dll as embedded resource in your project and use the AssemblyResolve event to load it, for example:
![lz4-embedded](https://cloud.githubusercontent.com/assets/9783218/26558277/c08d0438-44a7-11e7-9f7d-5ca78ac3582a.png)

```
namespace ConsoleApp1 {
	class Program {
		static void Main(string[] args) {

			AppDomain.CurrentDomain.AssemblyResolve += (semder2, args2) => {
				if (args2.Name.StartsWith("lz4.AnyCPU.loader,")) {
					using (Stream s = typeof(Program).Assembly.GetManifestResourceStream("ConsoleApp1.lz4.AnyCPU.loader.dll")) {
						byte[] b = new byte[s.Length];
						s.Read(b, 0, b.Length);
						return System.Reflection.Assembly.Load(b);
					}
				}
				return null;
			};

			TestCompress();

			return;
		}

		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
		private static void TestCompress() {
			byte[] data = new byte[32];
			using (RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider()) {
				rng.GetBytes(data);
			}

			var result = LZ4Helper.Compress(data);
		}
	}
}
```
