### ISSUE TITLE
Failure to decompress some files

### ISSUE THREAD

**Issue by AlexxEG** [IonKiwi/lz4.net#7]
Hey!

I've a program that uses this project to decompress files from Bethesda's BSA archives.

It works very well, but there are some rare cases where it throws "Decompress failed" exceptions. When I compare these files to files that do work I see little difference so I'm kinda lost as to why it doesn't work.

I'm attaching some files that you can use to replicate the issue. These files are **compressed**:
[replication.zip](https://github.com/IonKiwi/lz4.net/files/2281085/replication.zip)

Inside there is two files,
- compressed_truestorms-duststorm-high_lp.wav: **Causes error**
- compressed_truestorms-duststorm-interior_lp.wav:  **Works**

[Here is how I do the decompression (and also where the error is thrown)](https://github.com/AlexxEG/BSA_Browser/blob/f1e73bc13a6ec22171eb0c24875718e63f892208/Sharp.BSA.BA2/BSAUtil/BSAFileEntry.cs#L80)

Another program called [B.A.E.](https://www.nexusmods.com/fallout4/mods/78/) is able to extract these files correctly according to my users.

I would greatly appreciate any help!

**Comment by IonKiwi** [comment]
Hi,

Thank you for reporting this! and sorry for the delayed response.

It appears to be an issue with decompressing files which start with an uncompressed block.
The following compressed block uses the uncompressed block data as dictionary but is not instructed where to find it.

**Comment by AlexxEG** [comment]
I've tested it with the files I had issues with before and they all work now.

Thanks a lot!
